services:
  grafana:
    build: .
    container_name: grafana-sqlite
    ports:
      - "3000:3000"
    user: "0" # Ejecutar como root para evitar problemas de permisos
    volumes:
      - ./grafana-data:/var/lib/grafana   # Datos de grafana
      - ../containers.db:/db/containers.db  # Montamos la DB creada por GO
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=frser-sqlite-datasource
