FROM golang:1.22 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
WORKDIR /app/server
RUN go build -o server

FROM debian:bullseye-slim
WORKDIR /root/
COPY --from=builder /app/server/server .
CMD ["./server"]
