FROM golang:1.22 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
WORKDIR /app/client
RUN go build -o client

FROM debian:bullseye-slim
WORKDIR /root/
COPY --from=builder /app/client/client .
CMD ["./client"]
