FROM golang:1.24- AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
WORKDIR /app/server
RUN go build -o server server.go

FROM alpine:3.22
WORKDIR /root/
COPY --from=builder /app/server/server .
CMD ["./server"]
