# Usa imagen de Go para compilar dandole el tag de builder
FROM golang:1.22-alpine AS builder

# Directorio de trabajo
WORKDIR /app

# Copia archivos de dependencias
COPY go.mod go.sum .
# Descarga dependencias
RUN go mod download

# Copia el resto del código
COPY . .

# Limpia dependencias
RUN go mod tidy

# Compila la app
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/api .

# Usa imagen ligera para ejecutar
FROM alpine:3.22

# Directorio de trabajo
WORKDIR /app

# Copia el binario compilado desde el builder hacia el contenedor final
COPY --from=builder /app/api .

# Expone el puerto 8081
EXPOSE 8081

# Comando para ejecutar la aplicación (el binario compilado de GO)
CMD ["./api"]